name: Lint & Test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff mypy

      - name: Lint 
        run: |
          make lint

  test:
    runs-on: ubuntu-latest
    needs: format-lint 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # See: https://github.com/marketplace/actions/setup-micromamba
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true
          cache-environment-key: micromamba-env-${{ hashFiles('environment.yml') }}
          init-shell: >-
            bash

      - name: Install Neural-Bandits
        run: pip install -e .
        shell: micromamba-shell {0}

      - name: Run Mypy
        run: make mypy
        shell: micromamba-shell {0}

      - name: Run tests
        run: |
          make test
        shell: micromamba-shell {0}
      - name: Check Coverage
        run: |
          make coverage
        shell: micromamba-shell {0}